Support VeraCrypt export devices
freedomofpress/securedrop-export pull request #126
Opened 2023-10-05 01:16 UTC by rocodes

WIP

- Add basic detection/unlocking of veracrypt drives
- No changes to legacy_service.py (compatible with current securedrop-client)
- Experimental/wip changes to service.py to allow for detecting and unlocking veracrypt drives. Releasing these changes will deprecate the legacy files and should be done in coordination with corresponding client changes

Reviewers: See https://gist.github.com/rocodes/b2859584b7b3bd7c407e805575d4620c for quick veracrypt drive setup instructions

2023-12-01 02:59 UTC, cfm commented
Per handoff today: @legoktm will finalize tests next week, and I will review the week following.

2023-12-05 18:31 UTC, legoktm commented
CI is passing! Flipping to ready for review now :)

2023-12-05 18:53 UTC, legoktm commented on README.md
>  `device`
Need to change the line above that says "We do not yet support drives that use full-disk encryption with VeraCrypt." ;-)

2023-12-13 23:55 UTC, cfm requested changes
This is looking good.  I've left a few observations and nits inline, plus these questions:

This feels very state-mechanistic *especially* now that there is varying precision in what we can know about LUKS versus VeraCrypt volumes.  We don't have to worry about that here, since `send-to-usb` is a one-shot action at a particular time, but I'll raise this again in `securedrop-client`.

Re: <https://github.com/freedomofpress/securedrop-export/pull/126#issue-1927212851>:

> in order to accommodate different filesystems that could be inside Veracrypt containers re:mounting permissions, this PR introduces a change from using `sudo mount` to using `disksctl` to handle mounting and unmounting. However, I'd appreciate a review re: file system mounting permissions and if we're OK with the changes.

I'd like to understand better (before releasing if not as part of reviewing this feature) what you view as the changes in permissions and your concerns about them.  For a LUKS volume, at least, the permissions appear unchanged:

```sh-session
user@sd-app:~/QubesIncoming/sd-dev$ ls -al /media/user/
total 12
drwxr-x---+  3 root root 4096 Dec 13 15:48  .
drwxr-xr-x   3 root root 4096 Dec 13 11:54  ..
drwx------  24 user user 4096 Dec 13 15:05 'QA export_transf'
```

And *losing* `sudo` to un/mount devices seems at face value like a good thing, even if `sudo` is a passwordless operation in a Qubes VM anyway.

## Test plan

1. [x] **With `device: "disk-test"`:** No USBs connected: `NO_DEVICE_DETECTED`

3. [x] **With `device: "disk-test"`:** > 1 USBs connected: `MULTI_DEVICE_DETECTED`

4. [ ] **With `device: "disk-test"`:** Unsupported device connected (could be: device has 2 or more partitions, device has unrecognized encryption scheme, device is a locked VeraCrypt drive, which we won't support for now due to difficulty with error handling, or malformed device): `INVALID_DEVICE_DETECTED`

**No:** `UNKNOWN_DEVICE_DETECTED` (see case [7] below).

5. [x] **With `device: "disk-test"`:** 1 LUKS-formatted USB connected and it's locked: `DEVICE_LOCKED`

6. [x] **With `device: "disk-test"`:** 1 LUKS-formatted device (partition or whole device encrypted) connected and it's unlocked: `DEVICE_WRITABLE` (and device will be mounted in `/media/user`), or `SUCCESS_EXPORT` (depending on the command in metadata.json).

7. [ ] **With `device: "disk"`:**

```sh-session
user@sd-app:~/QubesIncoming/sd-dev$ lsblk /dev/sda
NAME           MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda              8:0    1 14.3G  0 disk  
└─sda1           8:1    1 14.3G  0 part  
  └─luks-e538abe0-cd9e-4eab-b1d5-fb652acc235b
               254:0    0 14.3G  0 crypt /media/user/QA export_transf
user@sd-app:~/QubesIncoming/sd-dev$ send-to-usb sample_export.sd_export.cfm
Usage:
  udisksctl unmount [OPTION…]

Unmount a filesystem.

Options:
  -p, --object-path         Object to unmount
  -b, --block-device        Block device to unmount
  -f, --force               Force/lazy unmount
  --no-user-interaction     Do not authenticate the user if needed

DEVICE_ERROR
```

Fix proposed in **TK**.

8. [ ] 1 Veracrypt-formatted device (parition or whole device encrypted) and it's unlocked: same as above

We shouldn't assume a single partition will be `/sdX1`:

```sh-session
user@sd-app:~/QubesIncoming/sd-dev$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    1 14.3G  0 disk 
└─sda2    8:2    1 14.1G  0 part 
xvda    202:0    0   10G  0 disk 
├─xvda1 202:1    0  200M  0 part 
├─xvda2 202:2    0    2M  0 part 
└─xvda3 202:3    0  9.8G  0 part /
xvdb    202:16   0   10G  0 disk /rw
xvdc    202:32   0   10G  0 disk 
├─xvdc1 202:33   0    1G  0 part [SWAP]
└─xvdc3 202:35   0    9G  0 part 
user@sd-app:~/QubesIncoming/sd-dev$ send-to-usb sample_export.sd_export
Device /dev/sda1 does not exist or access denied.
UNKNOWN_DEVICE_DETECTED
```

(Will this also be eased by rocodes/securedrop-export#1?)

9. [x] Other error statuses are fairly self explanatory (`ERROR_MOUNT`, `ERROR_CLEANUP`, etc)

2023-12-13 23:55 UTC, cfm commented on securedrop_export/disk/cli.py
> +                subprocess.check_call(["udisksctl", "unmount", volume.mountpoint])
`udisksctl unmount` appears to want `--block-device`, without which it errors out with its usage statement, so:

```suggestion
                subprocess.check_call(["udisksctl", "unmount", "--block-device", f"/dev/mapper/{volume.mapped_name}"])
```

2023-12-13 23:55 UTC, cfm commented on securedrop_export/disk/cli.py
> +        volume is mounted inside /media/user/ by udisksctl.
Mine mounts at `/media/user/${VOLUME_NAME}`.

2023-12-14 00:03 UTC, cfm commented
(@legoktm, I will resubmit this review in `securedrop-client` once this pull request gets migrated there.)

2023-12-14 20:07 UTC, cfm commented
Review copied to <https://github.com/freedomofpress/securedrop-client/pull/1669#pullrequestreview-1782626354>.

2023-12-14 20:07 UTC, closed without merging