Always communicate error messages to clients
freedomofpress/securedrop-export pull request #96
Opened 2022-06-30 21:21 UTC by eaon

Currently, `exit_gracefully` does not share the type of error with
the client if the `subprocess` exception that called the method captured any
output. This PR changes the current behaviour: users always see error messages we want them to see, and logs are populated in case of captured output.

Fixes #95

## Testing

As this is difficult to trigger "in the wild", I think the following is sufficient, but I'm open to switching to a more in-depth test plan that involves using the client and triggering an error with output deliberately:

- [ ] Make sure that the updated test is reasonable
- [ ] The test passes
- [ ] File export to USB devices operates as expected
- [ ] (Extended) If #93 was fixed, printing with the client behaves as expected

2022-07-01 02:02 UTC, creviera requested changes
The code change makes this clearer, and I believe it's now doing what we originally intended. 

- [x] (Optional, it is more efficient tho) Merge locally with #97 and review simultaneously
- [x] Make sure that the updated test is reasonable
- [x] The test passes
- :x: File export to USB devices operates as expected
  - Seeing `ERROR_USB_MOUNT: See your administrator for help`
- [x] (Optional) Printing works as expected

2022-07-01 02:04 UTC, creviera commented
Also, just running through the test plan on buster...

2022-07-01 02:25 UTC, creviera commented
Same issue above on buster... but also i just tested a build of `securedrop-export` and looks there's a similar issue on `main` (same error code `ERROR_USB_MOUNT` but this time a little more detail: `mount: /media/usb: /dev/mapper/luks-xxxxxxxx-xxxx-xxxx-xxxxxxxxxx already mounted on /media/usb`)... Tomorrow I can test with different devices, debug, and provide more details and steps for reproing. @eaon - when you ran this test, it worked for you? Could someone else confirm whether or not this works?

2022-07-01 04:59 UTC, eloquence commented
I gave it a quick spin; I build a package that pulls in the changes both in this PR and in #97, installed it in `sd-large-bullseye-template`, rebooted the template and `sd-devices`, verified that the newly installed package was installed in `sd-devices`, and verified that the file contents in `/opt/venvs/securedrop-export` included the changes in both PRs.

- [x] File export to USB devices operates as expected

I can't reproduce the issue you're seeing, Allie. One thing I would recommend we compare is the configuration of your `sys-usb` VM -- when you look at the Qube Settings, does it show `sd-fedora-dvm` as its template?

Printing against a non-printer device (e.g. with a storage device plugged in) results in the same error as before these PRs, "lpinfo: Bad file descriptor". But I'm not seeing any code to handle that case yet so I guess that's expected for now; not sure if it's a regression relative to how that case was handled on 4.0.

2022-07-01 16:40 UTC, eaon commented
Right, with both branches merged, printing and exporting works for me too.

- [x] Plugging in a LUKS encrypted stick allows me to export
- [x] Plugging in a non-encrypted stick prompts me to insert an encrypted USB drive
- [x] Plugging in a printer allows me to print
- [x] Not plugging in a printer prompts for printer to be plugged in

What I can't reproduce is @eloquence's "lpinfo: Bad file descriptor" report though, for me if no printer is plugged in but a USB device is, I just get asked to please connect a USB printer. I'm curious about the exact workflow with which you arrived there with these 2 PRs.

2022-07-01 17:54 UTC, eloquence commented
@eaon I only ever attached a LUKS-encrypted drive to this machine, and may have done a bunch of export attempts before trying "print" with the same device plugged in. The device was therefore probably already auto-attached to sd-devices by the time I pressed "Print" -- perhaps that makes a difference in behavior?

2022-07-01 19:08 UTC, eaon commented
Hmm, I did the same, export with printer connected, print with USB drive attached, print with USB drive attached but no printer attached, etc. etc. Did not stumble on the `lpinfo: Bad file descriptor` issue ever. But I've only seen that happen if CUPS isn't running, which it wouldn't if `sd-devices` didn't have/inherit the `cups` service/feature (which isn't in the main branch of `securedrop-workstation` yet: https://github.com/freedomofpress/securedrop-workstation/pull/795).

2022-07-01 21:05 UTC, eloquence commented
@eaon That's exactly it -- when I manually enable `cups` for `sd-devices`, I get the "Please connect a printer" message. (I didn't try your PR yet; I manually set the feature. Setting it for `sd-devices-dvm` was not sufficient; it only worked after I set it for `sd-devices` explicitly.)

2022-07-01 21:09 UTC, eaon commented
Ah right, OK, I guess that's because the feature "inheritance" happens on creation time so merely running `sdw-admin --apply` isn't enough if `sd-devices-dvm` already exists. An uninstall should delete it all though and a new install ought to "inherit" the cups service/feature correctly.

2022-07-01 23:25 UTC, creviera commented
> I can't reproduce the issue you're seeing, Allie. One thing I would recommend we compare is the configuration of your sys-usb VM -- when you look at the Qube Settings, does it show sd-fedora-dvm as its template?

Thanks for the suggestion- unfortunately, that's not it. But based on yours and Michael's successful test, I'll just do some more testing once this is on nightlies and report it in an issue. I tried a transfer device that works on 4.0 buster and a newly formatted luks-encrypted device, and same issue... so we'll see.

securedrop-export nightlies for buster will keep failing due to http://deb.debian.org/debian/pool/main/c/cups/libcups2_2.2.10-6+deb10u4_amd64.deb not being found, but since we'll be removing buster support soon, going to merge past this.

2022-07-01 23:26 UTC, creviera approved these changes
Approving based on our joint review and test

2022-07-01 23:27 UTC, creviera commented
@eloquence - feel free to merge past the test failure when you get a chance (I'm unable to).

2022-07-02 00:59 UTC, eloquence commented
Given that buster tests are expected to fail (and we can build from a previous release if we do need to release for buster), I've disabled the "pass checks" requirement for `test-buster`.

2022-07-02 00:59 UTC, merged